#pragma once

enum EEcsComponentType : int32
{
	AngularVelocity = 0,
	AggroRadius,
	CollisionEnabled,
	CollisionGridMember,
	CollisionShape,
	Cooldown,
	EntityGridHash,
	Health,
	MaxTargetDistance,
	MovementInput,
	NarrowPhaseCollisionCandidates,
	NarrowPhaseEntityContacts,
	Navmesh,
	NavmeshAgent,
	NavmeshPathRequest,
	NavmeshPathResponse,
	OneFrameMovementSequence,
	Position,
	Rotation,
	Transform,
	Scale,
	PureSphere,
	RampedMoveToEntity,
	Radius,
	Reserved,
	SpatialHashMember,
	Speed,
	Stationary,
	SyncTransformBackToUnreal,
	SystemTransformFromUnrealToEcs,
	TransformComponent,
	Velocity,
	TargetEntity,
	MAX,
};
